### ISSUE TITLE
polya_analysis

### ISSUE THREAD

**Issue by dywang0323** [paultsw/polya_analysis#2]
Hello Dr. Tang

  I'm trying to use the polyA_analysis workflow to analysis my nanorpore data, for now, albacore is no longer maintained, and I try to install albacore for a long time, it still doesn't work, so I'm writing to know, can I use Guppy to basecalling my data, and then use the workflow you developed, if so, how can I adjust the pepline.

  Thank you very much！

**Comment by paultsw** [comment]
Hi,

At [lines 168 & 169 of the makefile](https://github.com/paultsw/polya_analysis/blob/master/pipeline.make#L168), you can modify the executable to use Guppy instead of Albacore:

Change
```
# modify the following `BASECALL` variable to point to your copy of `read_fast5_basecaller.py` from albacore:
BASECALL=read_fast5_basecaller.py
BASECALL_OPTS=--worker_threads=$(THREADS) -f FLO-MIN107 -k SQK-RNA001 -q 0
```
to, e.g.,
```
BASECALL=guppy_basecaller # change this to the path of your executable for guppy
BASECALL_OPTS=--flowcell FLO-MIN107 --kit SQK-RNA001 -q 0
```
where you can add additional command line arguments to `BASECALL_OPTS` as you see fit (e.g. batch size, CUDA device, et cetera).

I think it should be fine to run the pipeline after that.

**Comment by dywang0323** [comment]
Thank you very much, I have tried, it works very well

  Thanks,
  Dongyu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by paultsw** [comment]
Glad to hear it!

If you don't have any other questions, I will close this issue.

**Comment by dywang0323** [comment]
Okay, thank you very much for the help

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by paultsw** [comment]
No problem! Happy to help!
